// <auto-generated />
using System;
using CityDriveManager.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace CityDriveManager.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260811151401_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.2")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            MySqlModelBuilderExtensions.AutoIncrementColumns(modelBuilder);

            modelBuilder.Entity("CityDriveManager.Models.PointOfInterest", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<double>("Latitude")
                        .HasColumnType("double");

                    b.Property<double>("Longitude")
                        .HasColumnType("double");

                    b.Property<string>("Name")
                        .HasColumnType("longtext");

                    b.Property<string>("PoiType")
                        .IsRequired()
                        .HasMaxLength(21)
                        .HasColumnType("varchar(21)");

                    b.HasKey("Id");

                    b.ToTable("PointsOfInterest");

                    b.HasDiscriminator<string>("PoiType").HasValue("PointOfInterest");

                    b.UseTphMappingStrategy();
                });

            modelBuilder.Entity("CityDriveManager.Models.Trip", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("DepartureDate")
                        .HasColumnType("datetime(6)");

                    b.Property<int>("EndPointId")
                        .HasColumnType("int");

                    b.Property<int>("StartPointId")
                        .HasColumnType("int");

                    b.Property<int>("Traffic")
                        .HasColumnType("int");

                    b.Property<int>("VehicleId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("EndPointId");

                    b.HasIndex("StartPointId");

                    b.HasIndex("VehicleId");

                    b.ToTable("Trips");
                });

            modelBuilder.Entity("CityDriveManager.Models.Vehicle", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Brand")
                        .HasColumnType("longtext");

                    b.Property<string>("Color")
                        .HasColumnType("longtext");

                    b.Property<int>("CurrentSpeed")
                        .HasColumnType("int");

                    b.Property<string>("VehicleType")
                        .IsRequired()
                        .HasMaxLength(13)
                        .HasColumnType("varchar(13)");

                    b.HasKey("Id");

                    b.ToTable("Vehicles");

                    b.HasDiscriminator<string>("VehicleType").HasValue("Vehicle");

                    b.UseTphMappingStrategy();
                });

            modelBuilder.Entity("CityDriveManager.Models.Campus", b =>
                {
                    b.HasBaseType("CityDriveManager.Models.PointOfInterest");

                    b.Property<int>("Capacity")
                        .HasColumnType("int");

                    b.HasDiscriminator().HasValue("Campus");
                });

            modelBuilder.Entity("CityDriveManager.Models.HistoricalMonument", b =>
                {
                    b.HasBaseType("CityDriveManager.Models.PointOfInterest");

                    b.Property<int>("BuildYear")
                        .HasColumnType("int");

                    b.HasDiscriminator().HasValue("HistoricalMonument");
                });

            modelBuilder.Entity("CityDriveManager.Models.Car", b =>
                {
                    b.HasBaseType("CityDriveManager.Models.Vehicle");

                    b.Property<string>("Model")
                        .HasColumnType("longtext");

                    b.HasDiscriminator().HasValue("Car");
                });

            modelBuilder.Entity("CityDriveManager.Models.HybridCar", b =>
                {
                    b.HasBaseType("CityDriveManager.Models.Vehicle");

                    b.Property<double>("BatteryLevel")
                        .HasColumnType("double");

                    b.Property<double>("FuelLevel")
                        .HasColumnType("double");

                    b.HasDiscriminator().HasValue("HybridCar");
                });

            modelBuilder.Entity("CityDriveManager.Models.Truck", b =>
                {
                    b.HasBaseType("CityDriveManager.Models.Vehicle");

                    b.Property<double>("Tonnage")
                        .HasColumnType("double");

                    b.HasDiscriminator().HasValue("Truck");
                });

            modelBuilder.Entity("CityDriveManager.Models.Trip", b =>
                {
                    b.HasOne("CityDriveManager.Models.PointOfInterest", "EndPoint")
                        .WithMany()
                        .HasForeignKey("EndPointId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("CityDriveManager.Models.PointOfInterest", "StartPoint")
                        .WithMany()
                        .HasForeignKey("StartPointId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("CityDriveManager.Models.Vehicle", "Vehicle")
                        .WithMany()
                        .HasForeignKey("VehicleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("EndPoint");

                    b.Navigation("StartPoint");

                    b.Navigation("Vehicle");
                });
#pragma warning restore 612, 618
        }
    }
}
